# video output
Output demo.gif

# styling
Set FontSize 24
Set Width 1080
Set Height 500
Set Margin 20
Set MarginFill "#255dd9"
Set BorderRadius 5
Set WindowBar Colorful

# act
Set TypingSpeed 0.5
Type yall
Enter
Sleep 1000ms

Down 
Down
Sleep 1000ms
Enter

Set TypingSpeed 1.2
Sleep 1000ms
Type "VSC"
Sleep 1000ms
Down
Sleep 1000ms
Enter

Set TypingSpeed 0.05
Type "...app is now launched in the foreground :D"
Sleep 1000ms

